{{- if .Values.frontend.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "neo-blog.fullname" . }}-frontend
  labels:
    {{- include "neo-blog.frontend.selectorLabels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "neo-blog.frontend.selectorLabels" . | nindent 4 }}
{{- end -}}